## Veri Manipülasyonu 

**Numpy** 

Numerical Python

- Bilimsel hesaplamalar için kullanılır.
- Arrayler / çok boyutlu arrayler ve matrisler üzerinde yüksek performanslı çalışma imkanı sağlar.
- Temelleri 1995'te (matrix-sig, Guido Van Rossum) atılmış nihai olarak 2005(Travis Oliphant) yılında hayata geçmiştir. 
- Listelere benzerdir, farkı; verimli veri saklama ve vektörel operasyonlardır. 

In [1]:
import numpy as np

In [4]:
#numpy array'i çağırmak

a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

In [3]:
a * b 

array([ 2,  6, 12, 20])

#### Numpy Array'i Oluşturmak

Veri tipidir. Tıpkı listeler gibi. 

In [13]:
# 0 dolu 

np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
# 1 den oluşan 

np.ones((3,5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [16]:
# 3 ile dolu liste yapmak

np.full((3,5), 3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [17]:
# 0 dan 31e kadar 3 arayla sayı oluştur

np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [19]:
#iki sayı arasında n kadar değer oluşturmak 

np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [21]:
#dağılımı kendiminizin belirlediği sayılar oluşturmak 
# ort 10 std 4 gibi

np.random.normal(10,4,(3,4)) 

array([[10.38996977,  5.15662122,  8.26833169,  2.64213453],
       [ 5.25453512,  4.58566416, 11.78541416,  6.24773029],
       [12.534119  ,  8.33083346, 16.83157859, 14.37100229]])

In [ ]:
# int değerlerden rastgele oluşturmak

np.random.randint(0,10,(3,4))

array([[6, 6, 4, 0],
       [6, 6, 6, 8],
       [5, 0, 7, 0]])

##### Numpy Array Özellikleri 

- **ndim**: Boyut Sayısı
- **shape**: Boyut Bilgisi
- **size**: Toplam Eleman SAyısı
- **stype**: Array Veri Tipi 

In [32]:
# 10 elemanlı 10'a kadar 

a = np.random.randint(10, size = 10)

In [33]:
a.ndim

1

In [34]:
a.shape

(10,)

In [35]:
a.size

10

In [37]:
a.dtype

dtype('int32')

In [38]:
# iki boyutlu oluşturma

b = np.random.randint(10, size = (3,5))

In [39]:
b

array([[7, 0, 3, 8, 5],
       [4, 2, 8, 7, 5],
       [6, 1, 0, 4, 8]])

In [41]:
b.ndim

2

In [42]:
b.size

15

In [44]:
b.shape

(3, 5)

In [45]:
b.dtype

dtype('int32')

#### Yeniden Şekillendirme ( Reshaping)

In [48]:
# Var olan bir numpy arrayini yeniden şekillendirme 

np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
#tek boyutlu bir vektördür

a = np.arange(1,10)

In [53]:
a.ndim

1

In [55]:
# iki boyutlu ancak tek liste gibi görünüyor çift [] lere dikkat.

b = a.reshape((1,9))

In [56]:
b.ndim

2

#### Array Birleştirme (Concantenation)

In [57]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [58]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [59]:
z = np.array([7,8,9])

In [60]:
np.concatenate([x,y,x])

array([1, 2, 3, 4, 5, 6, 1, 2, 3])

In [61]:
#iki boyut 

In [62]:
a = np.array([[1,2,3,],
              [4,5,6]])

In [63]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [65]:
np.concatenate([a,a], axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

#### Array Ayırma (Splitting)

In [66]:
x = np.array([1,2,3,99,99,3,2,1])

In [67]:
np.split(x, [3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [68]:
a,b,c = np.split(x, [3,5])

In [69]:
a

array([1, 2, 3])

In [70]:
b

array([99, 99])

In [71]:
c

array([3, 2, 1])

In [72]:
# iki boyutlu ayırma 

m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [73]:
np.vsplit(m, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [74]:
ust, alt = np.vsplit(m, [2])

In [75]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [76]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [77]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [78]:
#yatay bölme 

In [79]:
np.hsplit(m,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [80]:
sag, sol = np.hsplit(m,[2])

In [81]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [82]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

#### Array Sıralama (Sorting)

In [89]:
v = np.array([2,1,4,3,5])

In [90]:
v

array([2, 1, 4, 3, 5])

In [85]:
# orjinal yapıyı bozmuyor  
np.sort(v) 

array([1, 2, 3, 4, 5])

In [91]:
v

array([2, 1, 4, 3, 5])

In [92]:
# yapıyı komple değiştiriyor 
v.sort()

In [93]:
v

array([1, 2, 3, 4, 5])

In [94]:
# iki boyutlu array sıralama

m = np.random.normal (20,5, (3,3))

In [95]:
m

array([[29.82400586, 17.63974435, 16.13631185],
       [24.91324196, 19.82723341, 22.62772711],
       [19.89337053, 24.27559165, 22.66892367]])

In [96]:
# satırları sıralamak

np.sort(m, axis = 1) 

array([[16.13631185, 17.63974435, 29.82400586],
       [19.82723341, 22.62772711, 24.91324196],
       [19.89337053, 22.66892367, 24.27559165]])

In [97]:
# sutunları sıralamak

np.sort(m, axis = 0)

array([[19.89337053, 17.63974435, 16.13631185],
       [24.91324196, 19.82723341, 22.62772711],
       [29.82400586, 24.27559165, 22.66892367]])

#### Index ile Elemanlara Erişmek

In [98]:
a = np.random.randint(10, size = 10)
a 

array([2, 9, 9, 4, 9, 7, 7, 8, 5, 1])

In [99]:
a[0]

2

In [100]:
a[-1]

1

In [101]:
# 0.elemanı değiştirmek 

a[0] = 100 

In [102]:
a

array([100,   9,   9,   4,   9,   7,   7,   8,   5,   1])

In [103]:
m = np.random.randint(10, size = (3,5)) 
m

array([[0, 9, 3, 1, 9],
       [9, 5, 6, 7, 2],
       [1, 7, 6, 2, 2]])

In [104]:
m[0,0]

0

In [105]:
m[1,2]

6

In [106]:
m[1,2] = 88 

In [107]:
m

array([[ 0,  9,  3,  1,  9],
       [ 9,  5, 88,  7,  2],
       [ 1,  7,  6,  2,  2]])

In [108]:
# ondalıklı eklemek istersen normal sayı olarak ekler tipi sabit çünkü 

m[1,4] = 2.2 
m

array([[ 0,  9,  3,  1,  9],
       [ 9,  5, 88,  7,  2],
       [ 1,  7,  6,  2,  2]])

#### Slicing ile Elemanlara Erişmek / Array Alt Küme İşlemleri

In [109]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [110]:
a[0:3]

array([20, 21, 22])

In [111]:
# 0 dan 3 e kadar erişmek 

a[:3]

array([20, 21, 22])

In [112]:
# 3 ten 0 a kadar

a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [113]:
# 0. indexten başla 2 şer 2şer ilerle

a[0::2]

array([20, 22, 24, 26, 28])

In [114]:
# İki boyutlu slice işlemleri 

In [115]:
m = np.random.randint(10, size= (5,5))

In [116]:
m

array([[7, 7, 7, 1, 0],
       [8, 7, 1, 3, 6],
       [0, 6, 8, 1, 9],
       [0, 6, 2, 1, 3],
       [0, 7, 1, 6, 0]])

In [117]:
#bütün satırları seç şu sutunda seç

m[:,0]

array([7, 8, 0, 0, 0])

In [118]:
m[:,1]

array([7, 7, 6, 6, 7])

In [119]:
# sutunlarda seç şu satırda

m[0,:]

array([7, 7, 7, 1, 0])

In [120]:
m[0:2, 0:3]

array([[7, 7, 7],
       [8, 7, 1]])

In [121]:
m[:,0:2]

array([[7, 7],
       [8, 7],
       [0, 6],
       [0, 6],
       [0, 7]])

#### Alt küme Üzerinde İşlem Yapmak 

In [122]:
import numpy as np
a = np.random.randint(10, size =(5,5))
a

array([[8, 8, 4, 0, 1],
       [2, 1, 5, 6, 7],
       [8, 3, 6, 3, 5],
       [1, 3, 4, 8, 1],
       [2, 6, 4, 6, 5]])

In [123]:
alt_a = a[0:3, 0:2]
alt_a

array([[8, 8],
       [2, 1],
       [8, 3]])

In [124]:
alt_a[0,0] = 99999
alt_a[1,1] = 888

In [125]:
alt_a

array([[99999,     8],
       [    2,   888],
       [    8,     3]])

In [126]:
a

array([[99999,     8,     4,     0,     1],
       [    2,   888,     5,     6,     7],
       [    8,     3,     6,     3,     5],
       [    1,     3,     4,     8,     1],
       [    2,     6,     4,     6,     5]])

In [128]:
# ana listede de değişiklik yapar bunu yapmaması için copy ile ana kümedenn bağımsız hale getirmek gerekir 

In [134]:
alt_b = m[0:3, 0:2].copy()
alt_b

array([[7, 7],
       [8, 7],
       [0, 6]])

In [135]:
alt_b[0,0] = 9999

In [136]:
alt_b

array([[9999,    7],
       [   8,    7],
       [   0,    6]])

In [137]:
m

array([[7, 7, 7, 1, 0],
       [8, 7, 1, 3, 6],
       [0, 6, 8, 1, 9],
       [0, 6, 2, 1, 3],
       [0, 7, 1, 6, 0]])

### Fancy Index ile Elemanlara Erişmek 

In [139]:
v = np.arange(0, 30, 3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [140]:
v[1]

3

In [141]:
al_getir = [1,3,5]

In [142]:
v[al_getir]

array([ 3,  9, 15])

In [143]:
# iki boyutta fancy

In [144]:
m = np.arange(9).reshape((3,3))

In [145]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [146]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [147]:
m[satir,sutun]

array([1, 5])

In [148]:
# basit index ile fancy index
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [149]:
m[0,[1,2]]

array([1, 2])

In [150]:
#slice ile fancy

In [151]:
m[0:, [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

#### Koşullu Eleman İşlemleri 

In [152]:
v = np.array([1, 2, 3, 4, 5])

In [153]:
# burada sadece sorgu yapılıyor true veya false cevap donecek
v > 5 

array([False, False, False, False, False])

In [154]:
v < 3 

array([ True,  True, False, False, False])

In [156]:
# true olma durumuna gore elemanları getiriyor 

v[v < 3]

array([1, 2])

In [157]:
v[v > 3]

array([4, 5])

In [158]:
v[v == 3]

array([3])

In [159]:
# 3 dışındakileri getir 

v[v != 3]

array([1, 2, 4, 5])

In [161]:
v

array([1, 2, 3, 4, 5])

In [160]:
v * 2 

array([ 2,  4,  6,  8, 10])

In [162]:
v / 5 

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [163]:
v**2

array([ 1,  4,  9, 16, 25], dtype=int32)

#### Matematiksel İşlemler 

"ufunc" aracılığıyla yapılıyor aslında arka planda

In [164]:
v = np.array([1, 2, 3, 4, 5])

In [165]:
v

array([1, 2, 3, 4, 5])

In [166]:
v - 1 

array([0, 1, 2, 3, 4])

In [167]:
v*5/10 - 1 

array([-0.5,  0. ,  0.5,  1. ,  1.5])

In [168]:
#ucuncu dereceden kuvvet alma

np.power(v,3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [169]:
# v nin 2 ye bölümünden kalanı getir 

v % 2 

array([1, 0, 1, 0, 1], dtype=int32)

In [170]:
#veya 

np.mod(v,2)

array([1, 0, 1, 0, 1], dtype=int32)

In [172]:
# mutlak değer almak 

np.absolute(np.array([-3]))

array([3])

In [173]:
np.sin(360)

0.9589157234143065

In [175]:
np.cos(180)

-0.5984600690578581

In [178]:
v = np.array([1,2,3])

In [179]:
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [180]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [181]:
#numpyda bulunan matematiksel diğer fonksiyonlara nasıl ulaşırız?
# numpy cheat sheat i google da aratabilirsiniz. 
?np

Type:        module
String form: <module 'numpy' from 'C:\\Users\\furka\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\furka\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >

In [183]:
v.sum()

6

In [184]:
v.min()

1

In [185]:
v.max()

3

In [187]:
np.std(v, axis=0)

0.816496580927726

#### Numpy ile İki Bilinmeyenli Denklem Çözümü

In [188]:
import numpy as np

$ 5 * x_0 + x_1 = 12 $ \
$ x_0 + 3 * x_1 = 10 $


In [189]:
a = np.array([[5,1], [1,3]])
b = np.array([12,10])

In [190]:
a

array([[5, 1],
       [1, 3]])

In [191]:
b

array([12, 10])

In [194]:
x = np.linalg.solve(a,b)
x

array([1.85714286, 2.71428571])